### ISSUE TITLE
Trouble Opening PhamDB databases in phamerator

### ISSUE THREAD

**Issue by hhendrickson** [jglamine/phamdb#9]
Hi there, 

Thanks for making PhamDB. It's awesome to be able to make my own databases. 
I am trying to open the new databases in the SEA PHAGES VM but when I follow the instructions for adding the server and the database and then closing (whether or not I force database), I get the Database Setup Required, Password prompt from Phamerator. The VM is on line and can access my databases at the server site but not phamerator. I don't have a password on the phamDB databases and this just looks like an error. Am I missing a step?
Thanks! 

Heather

**Comment by jglamine** [comment]
Thanks for the bug report! Unfortunately, it's been a few years since I worked on this project and I don't remember the details well enough to help troubleshoot off the top of my head.

I have a few ideas.

Can you provide me with a screenshot of the error message you're getting?

Can you provide me with a screenshot of the setting you are using to connect to the database, and a screenshot of where you're getting that information from?

What version of the SEA PHAGES vm are you using? This application was developed with the 2015 VM, and it's possible that it doesn't work with the most recent version of Phamerator (I haven't tested it at least) and you might need to find the 2015 SEA PHAGES vm.

**Comment by hhendrickson** [comment]
Hey there! 

Thanks for coming back to me. The HHMI folks told me so needed to use the password ‘phage’ or ‘phages’ at the prompt. All sorted now! 

Thanks!
Heather

**Comment by jglamine** [comment]
Great, I'm glad things worked out!
